CREATE DATABASE EducacaoGamificada;

USE EducacaoGamificada;

CREATE TABLE USUARIO(
COD_USUARIO INT(10),
NOME_USUARIO VARCHAR(100), 
LOGIN VARCHAR(30),
SENHA VARCHAR(45),
EMAIL_USUARIO VARCHAR(100), 
CPF VARCHAR(11));

CREATE TABLE TIPO_USUARIO(
COD_USUARIO INT(10),
DESCRICAO_TIPO_USUARIO VARCHAR(300));

CREATE TABLE RANKING_USUARIO(
COD_USUARIO INT(10),
EMAIL_USUARIO VARCHAR(100),
NIVEL_USUARIO VARCHAR(20),
COINS_USUARIO INT(30),
TROFEUS_USUARIO VARCHAR(50),
MEDALHAS_USUARIO INT(30));

CREATE TABLE PLANOS_ASSINATURA(
ID_PLANO INT(10),
NOME_PLANO VARCHAR(100),
VALOR_PLANO INT(200));

CREATE TABLE PROFESSOR(
COD_PROFESSOR INT(10),
NOME_PROFESSOR VARCHAR(100),
EMAIL_PROFESSOR VARCHAR(100),
LOGIN VARCHAR(30),
SENHA VARCHAR(45),
CPF VARCHAR(11));

CREATE TABLE LANCAMENTO_ATIVIDADE(
ID_LANCAMENTO INT(20),
ID_ROTEIRO INT(20),
STATUS_LANCAMENTO VARCHAR(100),
DATA_HORA_LANCAMENTO DATETIME);

CREATE TABLE RESULTADOS_ATIVIDADE(
ID_RESULTADO_ATIVIDADE INT(20),
EMAIL_USUARIO VARCHAR(100),
ID_QUESTAO INT(20),
ALTERNATIVA_QUESTOES VARCHAR(10),
RESULTADO_ATIVIDADE INT(10));

CREATE TABLE ROTEIRO_ATIVIDADE(
ID_ROTEIRO_ATIVIDADES INT(20),
EMAIL_USUARIO VARCHAR(100),
NOME_ROTEIRO_ATIVIDADE VARCHAR(100));